[package]
name = "graph_reduce"
version = "0.1.0"
authors = ["Sam Miller <noogii7@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Simplify and sort directed acyclic graphs, and their associated matrices"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
